version: '3.9'

networks:
  internal:
    driver: bridge

services:

  nginx:

    image: nginx:latest
    restart: unless-stopped
    cpu_shares: 512
    mem_limit: 256M
    mem_reservation: 128M
    healthcheck:
      test: ["CMD", "service", "nginx", "status"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 5s
    ports:
      - '8080:80'
      - '8443:443'
    networks:
      - internal
    volumes:
      - ./www:/var/www
      - ./tmp:/tmp
      - ./log:/var/log/nginx
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/custom:/etc/nginx/custom
      - ./certs:/etc/nginx/certs
      
  php-fpm:
    build: .
    #image: php:8.3-fpm
    restart: unless-stopped
    cpu_shares: 512
    mem_limit: 512M
    mem_reservation: 256M
    healthcheck:
      test: ["CMD", "curl", "-A", "Docker", "-f", "http://nginx/health/php"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 5s
    networks:
      - internal
    volumes:
      - ./www:/var/www
      - ./tmp:/tmp
      - ./log:/var/log
      - ./php/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./php/php.ini:/usr/local/etc/php/conf.d/95-custom.ini
      
#  cert-generator:
#    image: alpine:latest
#    volumes:
#      - ./certs:/etc/nginx/certs
#    command: >
#      sh -c "apk --no-cache add openssl &&
#             openssl dhparam -out /etc/nginx/certs/dhparam.pem 2048 &&
#             openssl req -x509 -nodes -newkey rsa:2048 -keyout /etc/nginx/certs/selfsigned.key -out /etc/nginx/certs/selfsigned.crt -days 365 -subj '/CN=localhost'"
